### ISSUE TITLE
Does not Work on the current maui verision and nugat packages

### ISSUE THREAD

**Issue by s-beji** [naweed/MauiScientificCalculator#1]
The first problem: downgrades of packages is not allowed and must be corrected to use the latest.
Second problem the viewmodels don't work, I can't find the command "ICommand".

Please update this repo 

Thanks in advance

**Comment by naweed** [comment]
ICommand is replaced with RelayCommand in latest Toolkit.MVVM package.

I will update this sample to GS release soon.

**Comment by naweed** [comment]
Plz check again now. Update the repository to GA)

**Comment by s-beji** [comment]
Still the first named isshue exist

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Microsoft.Graphics.Win2D from 1.0.3.1 to 1.0.0.30. Reference the package directly from the project to select a different version. 
 MauiScientificCalculator -> Microsoft.Maui.Dependencies 6.0.312 -> Microsoft.Graphics.Win2D (>= 1.0.3.1) 
 MauiScientificCalculator -> Microsoft.Graphics.Win2D (>= 1.0.0.30)	MauiScientificCalculator	D:\DeepWorks Studios\Learn Assets\Maui\Projects\MauiScientificCalculator\src\MauiScientificCalculator.csproj	1

**Comment by s-beji** [comment]
![image](https://user-images.githubusercontent.com/59297046/173073206-0d4ac484-46f1-46a8-9c61-532acdfae775.png)
![image](https://user-images.githubusercontent.com/59297046/173073268-abb91408-cdcb-4348-8568-c74e8e10a8b4.png)

**Comment by s-beji** [comment]
At best you should take your time time to proper update this exsample because it wont be an easy fix it seems like those dependency causes all kind of trouble. Before you push the update check it yourself on the plattfroms with the updated version of vs 2022 aswell the dependencys and maui

Greetings

**Comment by s-beji** [comment]
Well after a little work i got nearly it running but now i get this 

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1130	Microsoft.Graphics.Canvas.winmd cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130	MauiScientificCalculator	C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	1007

**Comment by naweed** [comment]
Updated the project for Windows dependencies, but I have not tested for Windows. Plz do a pull request if any windows related changes are needed.

**Comment by naweed** [comment]
I will create it afresh using MAUI GA and update the sample soon.

**Comment by naweed** [comment]
Plz check now. I can confim to have tested it on Windows, Mac, iOS and Android.

**Comment by s-beji** [comment]
yes it works fine now thanks :)
